CREATE TABLE LB_PROFILE
(
LB_AK CHAR(11) PRIMARY KEY NOT NULL,
LB_VARDAS VARCHAR(255) NOT NULL,
LB_PAVARDE VARCHAR(255) NOT NULL,
LB_TELNR CHAR(9),
LB_GIMIMO_DATA DATE NOT NULL,
LB_LYTIS TINYINT NOT NULL,
)

CREATE TABLE PB_PROFILE
(
PB_SASKAITOS_NUMERIS VARCHAR(18) PRIMARY KEY NOT NULL,
PB_BANKAS VARCHAR(20),
LB_AK CHAR(11) FOREIGN KEY (LB_AK) REFERENCES LB_PROFILE(LB_AK),
PB_KREDITO_REITINGAS TINYINT,
PB_BALANSAS DECIMAL,
)
